version: '3.4'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword

  web:
    build: app
#    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      MYSQL_HOST: db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_DB: mydatabase
